# -*- coding: utf-8 -*-
"""speech to text.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BK1UMIHTsOfCi_f13zL6rmeWvXVxGK1g
"""

!pip install pyinstaller

##Text to text

language_from = input("Choose a language from which you need to convert : ") 
language_to=input("Choose the language to which you want to convert: ")
text=input("enter your text: ")
from translate import Translator
translator= Translator(to_lang=language)
translation = translator.translate(text)
print (translation)

"""#audio"""

import speech_recognition as sr

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/My Drive/learn it girl

r = sr.Recognizer()

harvard = sr.AudioFile('harvard.wav')
with harvard as source:
    audio = r.record(source)

type(audio)

r.recognize_google(audio)

with harvard as source:
    audio1 = r.record(source, duration=4)
    audio2 = r.record(source, duration=4)

r.recognize_google(audio1)

r.recognize_google(audio2)

with harvard as source:
     audio = r.record(source, offset=4.7, duration=2.8)

r.recognize_google(audio)

